In [1]:
####pandas
import pandas as pd 
print("import Sucessfully " )
import numpy as np

import Sucessfully

In [2]:
#data for dataframe
data = {'Name':['anshika','sania','lakshya','akshay'],
        'city':['kota','hyderabad','jaipur','delhi'],
        'branch':['cse','it','it','civil'],
        'roll_no':[10,20,30,40]}
data

{'Name': ['anshika', 'sania', 'lakshya', 'akshay'],
 'city': ['kota', 'hyderabad', 'jaipur', 'delhi'],
 'branch': ['cse', 'it', 'it', 'civil'],
 'roll_no': [10, 20, 30, 40]}

In [3]:
#create data frame 
df=pd.DataFrame(data)
df

      Name       city branch  roll_no
0  anshika       kota    cse       10
1    sania  hyderabad     it       20
2  lakshya     jaipur     it       30
3   akshay      delhi  civil       40

In [4]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [5]:
#df['Name'](Series)
df['Name']  #to acess the coloum

0    anshika
1      sania
2    lakshya
3     akshay
Name: Name, dtype: object

In [6]:
df.Name #to acess the coloum

0    anshika
1      sania
2    lakshya
3     akshay
Name: Name, dtype: object

In [7]:
arr = np.random.randint(1,200,50)
arr

array([ 35, 194,   4, 106,  70, 139, 137, 121, 160, 181,  84,  24,  64,
        66, 127, 174,   5,  99, 118, 106,  86, 150, 142, 109,  94, 101,
        53, 199, 151,  48, 122, 164,  45, 157,  66, 172,  45,   6, 129,
       155,  73, 108, 111,  78,  69, 103, 170,  34, 169, 191])

In [8]:
#creating the series fro the data 
ser=pd.Series(arr,name="randam_numbers",dtype="f")
ser

0      35.0
1     194.0
2       4.0
3     106.0
4      70.0
5     139.0
6     137.0
7     121.0
8     160.0
9     181.0
10     84.0
11     24.0
12     64.0
13     66.0
14    127.0
15    174.0
16      5.0
17     99.0
18    118.0
19    106.0
20     86.0
21    150.0
22    142.0
23    109.0
24     94.0
25    101.0
26     53.0
27    199.0
28    151.0
29     48.0
30    122.0
31    164.0
32     45.0
33    157.0
34     66.0
35    172.0
36     45.0
37      6.0
38    129.0
39    155.0
40     73.0
41    108.0
42    111.0
43     78.0
44     69.0
45    103.0
46    170.0
47     34.0
48    169.0
49    191.0
Name: randam_numbers, dtype: float32

In [9]:
ser[ser<50]  #to filtering the Series based in the condition

0     35.0
2      4.0
11    24.0
16     5.0
29    48.0
32    45.0
36    45.0
37     6.0
47    34.0
Name: randam_numbers, dtype: float32

In [10]:
ser[0]

35.0

In [11]:
ser[0:3]  # same rule Sciling Rule

0     35.0
1    194.0
2      4.0
Name: randam_numbers, dtype: float32

In [12]:
ser.min()

4.0

In [13]:
ser.max()

199.0

In [14]:
ser.mean()

106.28

In [15]:
ser.var()

2822.2058

In [16]:
ser.median()

107.0

In [17]:
ser.std()

53.124435

In [18]:
ser.sum()

5314.0

In [19]:
ser.agg(['min','max','mean','median','var','std','sum'])

min          4.000000
max        199.000000
mean       106.279999
median     107.000000
var       2822.205811
std         53.124435
sum       5314.000000
Name: randam_numbers, dtype: float32

In [20]:
df.shape #tells the shape of dataframe (Rows,Coloumns)

(4, 4)

In [21]:
df.info()  #Give the informations of the all the coloumns 
#   Column   Non-Null Count  Dtype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     4 non-null      object
 1   city     4 non-null      object
 2   branch   4 non-null      object
 3   roll_no  4 non-null      int64
dtypes: int64(1), object(3)
memory usage: 260.0+ bytes

In [22]:
df["Name"]#(Series)  #to acess the name Coloumns

0    anshika
1      sania
2    lakshya
3     akshay
Name: Name, dtype: object

In [23]:
df[["Name"]] #DataFrame

      Name
0  anshika
1    sania
2  lakshya
3   akshay

In [24]:
#DataFrame 
type(df[["Name"]])

pandas.core.frame.DataFrame

In [25]:
#Series 
type(df["Name"])

pandas.core.series.Series

In [26]:
#to Acess the multiple coloumns of DataFrame At Single time
df[['Name','city']]

      Name       city
0  anshika       kota
1    sania  hyderabad
2  lakshya     jaipur
3   akshay      delhi

In [27]:
df[['branch','Name']]  # to access multiple columns from a dataframe

  branch     Name
0    cse  anshika
1     it    sania
2     it  lakshya
3  civil   akshay

In [28]:
#LOC: Line Of Control (It use to Acess the Rows(Records) from the DataFrame ) 
df.loc[0]  # Acess the single row by using index of coloums

Name       anshika
city          kota
branch         cse
roll_no         10
Name: 0, dtype: object

In [29]:
df.loc[1]

Name           sania
city       hyderabad
branch            it
roll_no           20
Name: 1, dtype: object

In [30]:
#To acess the Multiple Coloumns OF DF by Slicing,
# inclusive,not indexed Based,Coloumns are Based  
df.loc[0:2]

      Name       city branch  roll_no
0  anshika       kota    cse       10
1    sania  hyderabad     it       20
2  lakshya     jaipur     it       30

In [31]:
#Exculsive ,Coloums are Specficed,Totally indexed Based 
df.iloc[0:2,1:3]

        city branch
0       kota    cse
1  hyderabad     it

In [32]:
df

      Name       city branch  roll_no
0  anshika       kota    cse       10
1    sania  hyderabad     it       20
2  lakshya     jaipur     it       30
3   akshay      delhi  civil       40

In [33]:
df.dtypes  #Tells the Datatype of the Every coloumns,
#Object -> Strings

Name       object
city       object
branch     object
roll_no     int64
dtype: object

In [34]:
df

      Name       city branch  roll_no
0  anshika       kota    cse       10
1    sania  hyderabad     it       20
2  lakshya     jaipur     it       30
3   akshay      delhi  civil       40

In [35]:
#df.loc[Rows_indexs,["Coloumns_Name"]]
df.loc[0:3,['branch']]

  branch
0    cse
1     it
2     it
3  civil

In [36]:
#min based on the Integer Values 
df.min()

Name       akshay
city        delhi
branch      civil
roll_no        10
dtype: object

In [37]:
#Max Based on the Integer Values 
df.max()

Name       sania
city        kota
branch        it
roll_no       40
dtype: object

In [38]:
df.describe() # it Prints the All Agreate  Functions

         roll_no
count   4.000000
mean   25.000000
std    12.909944
min    10.000000
25%    17.500000
50%    25.000000
75%    32.500000
max    40.000000

In [39]:
#O Stands for Objects 
df.describe(include="O") #O ==>object

           Name  city branch
count         4     4      4
unique        4     4      3
top     anshika  kota     it
freq          1     1      2

In [40]:
file_path=r"C:\Users\om\Desktop\Pandas\laptopPrice.csv"
#relative_path="laptopPrice.csv"

df=pd.read_csv(file_path) #read csv to convert the data in form of dataframe 
df
# Absolute path C:\Users\om\Desktop\Pandas\laptopPrice.csv
#Relative path laptopPrice.csv

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\om\\Desktop\\Pandas\\laptopPrice.csv'

In [41]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [42]:
df.head()  #return top 5 records

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0

In [43]:
df.head(40) #it return 40 records

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
5,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,22990,3 stars,0,0
6,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,21990,3 stars,31,3
7,ASUS,Intel,Core i5,10th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,58799,3 stars,0,0
8,Lenovo,Intel,Core i5,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,49999,3 stars,0,0
9,acer,AMD,Ryzen 5,10th,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,4 GB,Casual,No warranty,No,No,59990,4 stars,1946,240
10,acer,AMD,Ryzen 5,10th,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,6 GB,Casual,No warranty,No,No,93700,4 stars,259,47
11,acer,AMD,Ryzen 5,10th,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,4 GB,Casual,No warranty,No,No,72990,4 stars,425,67
12,Avita,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,17490,3 stars,1120,196
13,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,22990,3 stars,0,0
14,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,35990,3 stars,0,0
15,HP,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,No,56490,3 stars,0,0
16,HP,Intel,Core i5,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,65390,3 stars,0,0
17,Lenovo,Intel,Celeron Dual,Not Available,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,31999,4 stars,286,19
18,HP,Intel,Celeron Dual,Not Available,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,32490,4 stars,58,6
19,Lenovo,Intel,Celeron Dual,Not Available,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,31799,3 stars,0,0
20,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,29890,4 stars,7,0
21,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,23990,3 stars,15279,1947
22,HP,Intel,Core i3,7th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,32955,4 stars,311,27
23,HP,Intel,Core i5,7th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,46200,4 stars,47,7
24,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,34429,4 stars,37,6
25,Lenovo,Intel,Core i3,10th,8 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,ThinNlight,2 years,No,Yes,37990,4 stars,2080,235
26,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,1 year,No,Yes,35990,4 stars,1479,181
27,ASUS,Intel,Core i3,10th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,33980,4 stars,67,3
28,HP,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,39990,4 stars,273,30
29,DELL,Intel,Core i3,10th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,39490,4 stars,1267,171
30,HP,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,Yes,53990,4 stars,14,0
31,acer,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,38990,3 stars,0,0
32,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,37990,4 stars,284,39
33,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,37890,4 stars,44,5
34,Lenovo,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,38990,4 stars,33,4
35,Lenovo,Intel,Core i3,10th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,37990,4 stars,286,36
36,DELL,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,41990,3 stars,10,5
37,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,45990,4 stars,816,147
38,Lenovo,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,39990,4 stars,543,65
39,DELL,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,42490,4 stars,9,1

In [44]:
df.tail() #return 5 records of the bottom

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [45]:
df.tail(10)

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
813,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,162990,3 stars,0,0
814,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,130500,3 stars,0,0
815,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,No warranty,No,No,116990,3 stars,0,0
816,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,32-bit,6 GB,Casual,No warranty,No,No,138990,3 stars,0,0
817,ASUS,AMD,Ryzen 9,Not Available,4 GB,LPDDR4X,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,Yes,Yes,234990,3 stars,0,0
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              823 non-null    object
 1   processor_brand    823 non-null    object
 2   processor_name     823 non-null    object
 3   processor_gnrtn    823 non-null    object
 4   ram_gb             823 non-null    object
 5   ram_type           823 non-null    object
 6   ssd                823 non-null    object
 7   hdd                823 non-null    object
 8   os                 823 non-null    object
 9   os_bit             823 non-null    object
 10  graphic_card_gb    823 non-null    object
 11  weight             823 non-null    object
 12  warranty           823 non-null    object
 13  Touchscreen        823 non-null    object
 14  msoffice           823 non-null    object
 15  Price              823 non-null    int64
 16  rating             823 non-null    object
 17  Number of Ratings  823 non-null    int64
 18  Number of Reviews  823 non-null    int64
dtypes: int64(3), object(16)
memory usage: 122.3+ KB

In [47]:
df.describe()

               Price  Number of Ratings  Number of Reviews
count     823.000000         823.000000         823.000000
mean    76745.177400         315.301337          37.609964
std     45101.790525        1047.382654         121.728017
min     16990.000000           0.000000           0.000000
25%     46095.000000           0.000000           0.000000
50%     64990.000000          17.000000           2.000000
75%     89636.000000         139.500000          18.000000
max    441990.000000       15279.000000        1947.000000

In [48]:
#Select the Coloumns on the Based of Datatypes 
cat_col=df.select_dtypes(include="O")
cat_col.dtypes

brand              object
processor_brand    object
processor_name     object
processor_gnrtn    object
ram_gb             object
ram_type           object
ssd                object
hdd                object
os                 object
os_bit             object
graphic_card_gb    object
weight             object
warranty           object
Touchscreen        object
msoffice           object
rating             object
dtype: object

In [49]:
num_col=df.select_dtypes(exclude="O")
num_col.dtypes

Price                int64
Number of Ratings    int64
Number of Reviews    int64
dtype: object

In [50]:
#Returns the  Records of the DF  
num_col.head()

   Price  Number of Ratings  Number of Reviews
0  34649                  3                  0
1  38999                 65                  5
2  39999                  8                  1
3  69990                  0                  0
4  26990                  0                  0

In [51]:
cat_col.shape,num_col.shape

((823, 16), (823, 3))

In [52]:
#it Is combined the coloums 
pd.concat([cat_col,num_col],axis=1) #axis="coloums-1"
#axis="row-0"

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,rating,Price,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,2 stars,34649,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,3 stars,38999,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,3 stars,39999,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,3 stars,69990,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,3 stars,26990,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,3 stars,135990,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,3 stars,144990,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,3 stars,149990,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,3 stars,142990,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,4 stars,57490,18,4

In [53]:
#ti returns the Data of Brands Series 
df['brand']

0        ASUS
1      Lenovo
2      Lenovo
3        ASUS
4        ASUS
        ...
818      ASUS
819      ASUS
820      ASUS
821      ASUS
822    Lenovo
Name: brand, Length: 823, dtype: object

In [54]:
It returns the Unique Values of this coloumns 
df['brand'].unique()

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [55]:
#define the number of the Values of Unique Records of the coloumns 
df['brand'].nunique()

8

In [56]:
#it Returns the Sepecific No of Values of the particular values 
df['brand'].value_counts()

brand
ASUS      249
DELL      151
Lenovo    144
HP        136
acer       51
MSI        50
APPLE      28
Avita      14
Name: count, dtype: int64

In [57]:
#It Returns in the Acesding Order 
df['brand'].value_counts(ascending=True)

brand
Avita      14
APPLE      28
MSI        50
acer       51
HP        136
Lenovo    144
DELL      151
ASUS      249
Name: count, dtype: int64

In [58]:
df['ram_gb'].unique

<bound method Series.unique of 0      4 GB
1      4 GB
2      4 GB
3      8 GB
4      4 GB
       ...
818    4 GB
819    4 GB
820    4 GB
821    4 GB
822    8 GB
Name: ram_gb, Length: 823, dtype: object>

In [59]:
df['ram_gb'].value_counts()

ram_gb
8 GB     418
4 GB     226
16 GB    177
32 GB      2
Name: count, dtype: int64

In [ ]:
#It Filters the records acording to Conditions 
df['brand']=='APPLE'

KeyError: 'brand'

In [61]:
apple=df[df['brand']=='APPLE']

In [62]:
apple.shape

(28, 19)

In [63]:
apple.head()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
309,APPLE,Intel,Core i5,10th,8 GB,LPDDR4X,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,159990,4 stars,32,5
310,APPLE,Intel,Core i5,8th,8 GB,DDR3,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,172090,4 stars,108,13
407,APPLE,Intel,Core i5,10th,16 GB,LPDDR4X,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,179990,4 stars,31,3
408,APPLE,Intel,Core i5,10th,16 GB,LPDDR4X,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,179990,4 stars,91,5
599,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,85990,4 stars,6725,629

In [64]:
#Filter the Records on the particular Condtions 
#brand=="apple" and processor_brand=M
apple_m1chip=df[(df['brand']=="APPLE") & (df["processor_brand"]=="M1")]
apple_m1chip

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
599,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,85990,4 stars,6725,629
600,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,112990,4 stars,640,70
601,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
602,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,112990,4 stars,640,70
603,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,132990,4 stars,640,70
604,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
605,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,85990,4 stars,6725,629
606,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,149990,4 stars,640,70
607,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,125990,4 stars,399,45
608,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,103990,4 stars,809,91
609,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,101990,4 stars,809,91
610,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,6725,629
611,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,131990,4 stars,399,45
612,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,128990,4 stars,45,4
613,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,184990,4 stars,42,8
614,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8
615,APPLE,M1,M1,10th,4 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,124990,4 stars,45,4
616,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,6725,629
617,APPLE,M1,M1,10th,8 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,149990,4 stars,640,70
618,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,169990,4 stars,640,70
619,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8
620,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,243990,4 stars,42,8
621,APPLE,M1,M1,10th,32 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,309990,5 stars,3,1
622,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8

In [65]:
gb16=apple_m1chip[apple_m1chip['ram_gb']=="16 GB"]

In [66]:
gb16.shape

(11, 19)

In [67]:
gb16

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
601,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
603,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,132990,4 stars,640,70
604,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
606,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,149990,4 stars,640,70
612,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,128990,4 stars,45,4
613,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,184990,4 stars,42,8
614,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8
618,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,169990,4 stars,640,70
619,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8
620,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,243990,4 stars,42,8
622,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8

In [68]:
data=df[(df['brand']=="ASUS") & (df["processor_name"]=="Core i3") & (df['os']=="Windows")]
data.shape

(49, 19)

In [69]:
data.to_csv("data.csv",index="False")

In [70]:
pd.read_excel("data.xlsx")

,Unnamed: 0,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,14,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,35990,3 stars,0,0
2,24,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,34429,4 stars,37,6
3,26,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,1 year,No,Yes,35990,4 stars,1479,181
4,27,ASUS,Intel,Core i3,10th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,33980,4 stars,67,3
5,32,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,37990,4 stars,284,39
6,33,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,37890,4 stars,44,5
7,37,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,45990,4 stars,816,147
8,42,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,36990,4 stars,20,1
9,45,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,45990,4 stars,816,147
10,52,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,38490,3 stars,19,3
11,60,ASUS,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,35990,3 stars,0,0
12,66,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,39990,4 stars,181,19
13,68,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,41990,3 stars,0,0
14,70,ASUS,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,39990,3 stars,0,0
15,74,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,48490,3 stars,0,0
16,81,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,36990,4 stars,70,9
17,83,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,48990,3 stars,0,0
18,86,ASUS,Intel,Core i3,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,37990,4 stars,990,108
19,89,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,35990,4 stars,130,12
20,90,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,42990,4 stars,30,4
21,91,ASUS,Intel,Core i3,11th,8 GB,LPDDR4X,512 GB,0 GB,Windows,32-bit,0 GB,Casual,1 year,Yes,Yes,51990,4 stars,6,2
22,92,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,48990,4 stars,174,30
23,93,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,42990,4 stars,40,7
24,98,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,39990,4 stars,2551,297
25,102,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,41990,3 stars,0,0
26,104,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,44990,4 stars,2058,305
27,107,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,42990,4 stars,74,11
28,112,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,44990,3 stars,0,0
29,117,ASUS,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,51649,3 stars,0,0
30,119,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,40990,4 stars,4008,519
31,120,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,42990,4 stars,1869,234
32,121,ASUS,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,44890,3 stars,7,0
33,122,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,41490,4 stars,4008,519
34,125,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,40990,4 stars,4008,519
35,130,ASUS,Intel,Core i3,10th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,32890,3 stars,28,4
36,136,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,35990,3 stars,17,0
37,139,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,34990,3 stars,4203,490
38,140,ASUS,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,38900,3 stars,13,0
39,148,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,ThinNlight,No warranty,No,No,35590,3 stars,12,1
40,150,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,38990,4 stars,1850,216
41,151,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,ThinNlight,No warranty,No,No,33990,3 stars,43,7
42,156,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38000,4 stars,7,0
43,160,ASUS,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,41500,3 stars,4,0
44,165,ASUS,Intel,Core i3,10th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,32990,2 stars,12,0
45,166,ASUS,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,38680,3 stars,17,1
46,169,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,33990,3 stars,31,6
47,174,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,41890,4 stars,53,6
48,180,ASUS,Intel,Core i3,10th,4 GB,DDR4,256 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,40990,3 stars,0,0

In [71]:
#09-01-2025
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [72]:
df.head()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0

In [73]:
#ti returns the list of coloumns in the data Frams
df.columns

Index(['brand', 'processor_brand', 'processor_name', 'processor_gnrtn',
       'ram_gb', 'ram_type', 'ssd', 'hdd', 'os', 'os_bit', 'graphic_card_gb',
       'weight', 'warranty', 'Touchscreen', 'msoffice', 'Price', 'rating',
       'Number of Ratings', 'Number of Reviews'],
      dtype='object')

In [74]:
print("Total no of coloumns :",len(df.columns))

Total no of coloumns : 19

In [75]:
#it change the name of coloumns 
df.rename({"brand": "brands"},axis=1)

,brands,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [76]:
df.rename({0:"R"})  #axis=0 writing opreation

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
R,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [77]:
#it apply the Permanent changes in the Data Frame by help of inplace paramenter 
df.rename({"brand":"brands"},inplace=True,axis=1)

In [78]:
df

,brands,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [79]:
df=df.rename({"brand" : 'brands'},axis=1) #columns rename

In [80]:
df

,brands,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [81]:
df.columns=['brands', 'processor_brand', 'processor_name', 'processor_gnrtn',
       'ram_gb', 'ram_type', 'SSD', 'HDD', 'os', 'os_bit', 'graphic_card_gb',
       'weight', 'warranty', 'Touchscreen', 'msoffice', 'Price', 'rating',
       'Number of Ratings', 'Number of Reviews'] #method 2 to rename coloumns

In [82]:
df

,brands,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,SSD,HDD,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [83]:
#Manuplating the Data of the coloumns 
df['Number of Ratings']+5

0       8
1      70
2      13
3       5
4       5
       ..
818     5
819     5
820     5
821     5
822    23
Name: Number of Ratings, Length: 823, dtype: int64

In [84]:
df['Number of Ratings']+5

0       8
1      70
2      13
3       5
4       5
       ..
818     5
819     5
820     5
821     5
822    23
Name: Number of Ratings, Length: 823, dtype: int64

In [85]:
df['Number of Reviews']+10

0      10
1      15
2      11
3      10
4      10
       ..
818    10
819    10
820    10
821    10
822    14
Name: Number of Reviews, Length: 823, dtype: int64

In [86]:
#adding the new coloumns in the Dataframe 
df['New_column']=df['Number of Reviews']+10

In [87]:
df

,brands,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,SSD,HDD,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews,New_column
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0,10
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5,15
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1,11
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0,10
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0,10
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0,10
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0,10
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0,10
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4,14

In [88]:
df['New_column2']=df['Number of Reviews']+df["Number of Ratings"]

In [89]:
df

,brands,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,SSD,HDD,os,os_bit,...,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews,New_column,New_column2
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,...,Casual,No warranty,No,No,34649,2 stars,3,0,10,3
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,...,Casual,No warranty,No,No,38999,3 stars,65,5,15,70
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,...,Casual,No warranty,No,No,39999,3 stars,8,1,11,9
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,...,Casual,No warranty,No,No,69990,3 stars,0,0,10,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,...,Casual,No warranty,No,No,26990,3 stars,0,0,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,...,Casual,1 year,No,No,135990,3 stars,0,0,10,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,...,Casual,1 year,No,No,144990,3 stars,0,0,10,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,...,Casual,1 year,No,No,149990,3 stars,0,0,10,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,...,Casual,1 year,No,No,142990,3 stars,0,0,10,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,...,ThinNlight,No warranty,No,No,57490,4 stars,18,4,14,22

In [90]:
#df.drop("new_column")  #delete one columns
df.drop(["New_column","New_column2"],axis=1,inplace=True)  #delete multiple columns

In [91]:
df

,brands,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,SSD,HDD,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [92]:
df.head()

,brands,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,SSD,HDD,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0

In [93]:
df.index

RangeIndex(start=0, stop=823, step=1)

In [94]:
list(df.index)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822]

In [95]:
df.drop(1)

,brands,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,SSD,HDD,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
5,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,22990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [96]:
#no reasign 
df[df["brands"]=="APPLE"]

,brands,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,SSD,HDD,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
309,APPLE,Intel,Core i5,10th,8 GB,LPDDR4X,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,159990,4 stars,32,5
310,APPLE,Intel,Core i5,8th,8 GB,DDR3,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,172090,4 stars,108,13
407,APPLE,Intel,Core i5,10th,16 GB,LPDDR4X,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,179990,4 stars,31,3
408,APPLE,Intel,Core i5,10th,16 GB,LPDDR4X,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,179990,4 stars,91,5
599,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,85990,4 stars,6725,629
600,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,112990,4 stars,640,70
601,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
602,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,112990,4 stars,640,70
603,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,132990,4 stars,640,70
604,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
605,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,85990,4 stars,6725,629
606,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,149990,4 stars,640,70
607,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,125990,4 stars,399,45
608,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,103990,4 stars,809,91
609,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,101990,4 stars,809,91
610,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,6725,629
611,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,131990,4 stars,399,45
612,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,128990,4 stars,45,4
613,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,184990,4 stars,42,8
614,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8
615,APPLE,M1,M1,10th,4 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,124990,4 stars,45,4
616,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,6725,629
617,APPLE,M1,M1,10th,8 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,149990,4 stars,640,70
618,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,169990,4 stars,640,70
619,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8
620,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,243990,4 stars,42,8
621,APPLE,M1,M1,10th,32 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,309990,5 stars,3,1
622,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8

In [97]:
apple=df[df["brands"]=="APPLE"]
apple.shape

(28, 19)

In [98]:
list(range(0,28))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27]

In [99]:
apple.index=list(range(0,28))  #manual Process

In [100]:
apple

,brands,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,SSD,HDD,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,APPLE,Intel,Core i5,10th,8 GB,LPDDR4X,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,159990,4 stars,32,5
1,APPLE,Intel,Core i5,8th,8 GB,DDR3,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,172090,4 stars,108,13
2,APPLE,Intel,Core i5,10th,16 GB,LPDDR4X,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,179990,4 stars,31,3
3,APPLE,Intel,Core i5,10th,16 GB,LPDDR4X,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,179990,4 stars,91,5
4,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,85990,4 stars,6725,629
5,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,112990,4 stars,640,70
6,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
7,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,112990,4 stars,640,70
8,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,132990,4 stars,640,70
9,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
10,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,85990,4 stars,6725,629
11,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,149990,4 stars,640,70
12,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,125990,4 stars,399,45
13,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,103990,4 stars,809,91
14,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,101990,4 stars,809,91
15,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,6725,629
16,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,131990,4 stars,399,45
17,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,128990,4 stars,45,4
18,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,184990,4 stars,42,8
19,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8
20,APPLE,M1,M1,10th,4 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,124990,4 stars,45,4
21,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,6725,629
22,APPLE,M1,M1,10th,8 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,149990,4 stars,640,70
23,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,169990,4 stars,640,70
24,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8
25,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,243990,4 stars,42,8
26,APPLE,M1,M1,10th,32 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,309990,5 stars,3,1
27,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8

In [101]:
apple=df[df["brands"]=="APPLE"]

In [102]:
apple

,brands,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,SSD,HDD,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
309,APPLE,Intel,Core i5,10th,8 GB,LPDDR4X,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,159990,4 stars,32,5
310,APPLE,Intel,Core i5,8th,8 GB,DDR3,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,172090,4 stars,108,13
407,APPLE,Intel,Core i5,10th,16 GB,LPDDR4X,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,179990,4 stars,31,3
408,APPLE,Intel,Core i5,10th,16 GB,LPDDR4X,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,179990,4 stars,91,5
599,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,85990,4 stars,6725,629
600,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,112990,4 stars,640,70
601,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
602,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,112990,4 stars,640,70
603,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,132990,4 stars,640,70
604,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
605,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,85990,4 stars,6725,629
606,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,149990,4 stars,640,70
607,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,125990,4 stars,399,45
608,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,103990,4 stars,809,91
609,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,101990,4 stars,809,91
610,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,6725,629
611,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,131990,4 stars,399,45
612,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,128990,4 stars,45,4
613,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,184990,4 stars,42,8
614,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8
615,APPLE,M1,M1,10th,4 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,124990,4 stars,45,4
616,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,6725,629
617,APPLE,M1,M1,10th,8 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,149990,4 stars,640,70
618,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,169990,4 stars,640,70
619,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8
620,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,243990,4 stars,42,8
621,APPLE,M1,M1,10th,32 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,309990,5 stars,3,1
622,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8

In [103]:
apple.reset_index()

,index,brands,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,SSD,HDD,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,309,APPLE,Intel,Core i5,10th,8 GB,LPDDR4X,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,159990,4 stars,32,5
1,310,APPLE,Intel,Core i5,8th,8 GB,DDR3,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,172090,4 stars,108,13
2,407,APPLE,Intel,Core i5,10th,16 GB,LPDDR4X,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,179990,4 stars,31,3
3,408,APPLE,Intel,Core i5,10th,16 GB,LPDDR4X,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,179990,4 stars,91,5
4,599,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,85990,4 stars,6725,629
5,600,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,112990,4 stars,640,70
6,601,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
7,602,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,112990,4 stars,640,70
8,603,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,132990,4 stars,640,70
9,604,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
10,605,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,85990,4 stars,6725,629
11,606,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,149990,4 stars,640,70
12,607,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,125990,4 stars,399,45
13,608,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,103990,4 stars,809,91
14,609,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,101990,4 stars,809,91
15,610,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,6725,629
16,611,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,131990,4 stars,399,45
17,612,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,128990,4 stars,45,4
18,613,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,184990,4 stars,42,8
19,614,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8
20,615,APPLE,M1,M1,10th,4 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,124990,4 stars,45,4
21,616,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,6725,629
22,617,APPLE,M1,M1,10th,8 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,149990,4 stars,640,70
23,618,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,169990,4 stars,640,70
24,619,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8
25,620,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,243990,4 stars,42,8
26,621,APPLE,M1,M1,10th,32 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,309990,5 stars,3,1
27,622,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8

In [104]:
apple.reset_index(drop=True)

,brands,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,SSD,HDD,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,APPLE,Intel,Core i5,10th,8 GB,LPDDR4X,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,159990,4 stars,32,5
1,APPLE,Intel,Core i5,8th,8 GB,DDR3,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,172090,4 stars,108,13
2,APPLE,Intel,Core i5,10th,16 GB,LPDDR4X,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,179990,4 stars,31,3
3,APPLE,Intel,Core i5,10th,16 GB,LPDDR4X,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,179990,4 stars,91,5
4,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,85990,4 stars,6725,629
5,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,112990,4 stars,640,70
6,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
7,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,112990,4 stars,640,70
8,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,132990,4 stars,640,70
9,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
10,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,85990,4 stars,6725,629
11,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,149990,4 stars,640,70
12,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,125990,4 stars,399,45
13,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,103990,4 stars,809,91
14,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,101990,4 stars,809,91
15,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,6725,629
16,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,131990,4 stars,399,45
17,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,128990,4 stars,45,4
18,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,184990,4 stars,42,8
19,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8
20,APPLE,M1,M1,10th,4 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,124990,4 stars,45,4
21,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,6725,629
22,APPLE,M1,M1,10th,8 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,149990,4 stars,640,70
23,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,169990,4 stars,640,70
24,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8
25,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,243990,4 stars,42,8
26,APPLE,M1,M1,10th,32 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,309990,5 stars,3,1
27,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8

apple

In [105]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
818    False
819    False
820    False
821    False
822    False
Length: 823, dtype: bool

In [106]:
print("Duplicates Records : ",df.duplicated().sum())

Duplicates Records :  21

In [107]:
df[df.duplicated()]

,brands,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,SSD,HDD,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
13,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,22990,3 stars,0,0
45,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,45990,4 stars,816,147
125,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,40990,4 stars,4008,519
182,DELL,Intel,Core i3,11th,4 GB,DDR4,256 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,43590,3 stars,0,0
265,ASUS,Intel,Core i5,11th,16 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,59990,3 stars,0,0
352,ASUS,Intel,Core i5,11th,8 GB,LPDDR4X,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,84990,3 stars,0,0
375,ASUS,Intel,Core i5,11th,8 GB,LPDDR4X,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,No,99990,3 stars,0,0
391,Avita,Intel,Core i5,7th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,65556,3 stars,0,0
393,Avita,Intel,Core i5,7th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,65556,3 stars,0,0
399,Avita,Intel,Core i5,8th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,73063,3 stars,17,3
480,Avita,Intel,Core i7,8th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,73990,3 stars,0,0
481,Avita,Intel,Core i7,8th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,73990,3 stars,0,0
482,Avita,Intel,Core i7,8th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,73990,3 stars,0,0
483,Avita,Intel,Core i7,8th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,73990,3 stars,0,0
484,Avita,Intel,Core i7,8th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,73990,3 stars,0,0
530,DELL,Intel,Core i7,11th,16 GB,DDR4,512 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,99990,3 stars,0,0
602,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,112990,4 stars,640,70
604,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
605,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,85990,4 stars,6725,629
616,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,6725,629
622,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8

In [108]:
#it Delete the duplicate records permantly 
df.drop_duplicates(inplace=True)

In [109]:
df.shape

(802, 19)

In [110]:
print("Duplicates Records : ",df.duplicated().sum())

Duplicates Records :  0

In [ ]:
#missing value Imputation

In [111]:
#it print Those Row which have NaM value 
df.isnull()

,brands,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,SSD,HDD,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
819,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
820,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
821,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
822,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [114]:
df[df.isnull()]

,brands,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,SSD,HDD,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
819,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
820,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
822,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [115]:
df.isnull().sum()

brands               0
processor_brand      0
processor_name       0
processor_gnrtn      0
ram_gb               0
ram_type             0
SSD                  0
HDD                  0
os                   0
os_bit               0
graphic_card_gb      0
weight               0
warranty             0
Touchscreen          0
msoffice             0
Price                0
rating               0
Number of Ratings    0
Number of Reviews    0
dtype: int64

In [116]:
df.isnull().sum().sum()

0

In [117]:
data = {'A':[2,5,6,np.nan,8],
        'B':[np.nan,np.nan,8,5,6],
        'D':[7,4,5,8,9],
        'E':[8,4,5,np.nan,10]}
data

{'A': [2, 5, 6, nan, 8],
 'B': [nan, nan, 8, 5, 6],
 'D': [7, 4, 5, 8, 9],
 'E': [8, 4, 5, nan, 10]}

In [118]:
df=pd.DataFrame(data)
df

     A    B  D     E
0  2.0  NaN  7   8.0
1  5.0  NaN  4   4.0
2  6.0  8.0  5   5.0
3  NaN  5.0  8   NaN
4  8.0  6.0  9  10.0

In [119]:
df.isnull().sum()

A    1
B    2
D    0
E    1
dtype: int64

In [121]:
df.isnull().sum()

A    1
B    2
D    0
E    1
dtype: int64

In [120]:
df.isnull().sum().sum()

4

In [122]:
#it Delete the those records which have contains the null values 
df.dropna()

     A    B  D     E
2  6.0  8.0  5   5.0
4  8.0  6.0  9  10.0

In [123]:
df.dropna(axis=1)

   D
0  7
1  4
2  5
3  8
4  9

In [125]:
#it fills the Null value with constant number in the coloumns A 
df["A"].fillna(100)

0      2.0
1      5.0
2      6.0
3    100.0
4      8.0
Name: A, dtype: float64

In [81]:
import pandas as pd 
data = {"Test":['A','B','C','A','D','A','E']}
df = pd.DataFrame(data)
df

  Test
0    A
1    B
2    C
3    A
4    D
5    A
6    E

In [82]:
df.describe(include="O")

       Test
count     7
unique    5
top       A
freq      3

In [83]:
#10-01-2025
df=pd.read_csv("laptopPrice.csv")
df.head()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0

In [86]:
df['Number of Ratings'].dtype

dtype('int64')

In [87]:
df.dtypes

brand                object
processor_brand      object
processor_name       object
processor_gnrtn      object
ram_gb               object
ram_type             object
ssd                  object
hdd                  object
os                   object
os_bit               object
graphic_card_gb      object
weight               object
warranty             object
Touchscreen          object
msoffice             object
Price                 int64
rating               object
Number of Ratings     int64
Number of Reviews     int64
dtype: object

In [89]:
#to conversion of the datatype 
df['Number of Ratings'].astype(float)

0       3.0
1      65.0
2       8.0
3       0.0
4       0.0
       ...
818     0.0
819     0.0
820     0.0
821     0.0
822    18.0
Name: Number of Ratings, Length: 823, dtype: float64

In [90]:
df['Number of Ratings']=df['Number of Ratings'].astype(float)

In [91]:
df['Number of Ratings']

0       3.0
1      65.0
2       8.0
3       0.0
4       0.0
       ...
818     0.0
819     0.0
820     0.0
821     0.0
822    18.0
Name: Number of Ratings, Length: 823, dtype: float64

In [92]:
#To conversion of the integers 

df['Number of Ratings']=df['Number of Ratings'].astype("i")

In [93]:
df['Number of Ratings']

0       3
1      65
2       8
3       0
4       0
       ..
818     0
819     0
820     0
821     0
822    18
Name: Number of Ratings, Length: 823, dtype: int32

In [94]:
df.at[0,'brand']  #single handed

'ASUS'

In [95]:
df.at[0,'Price']

34649

In [96]:
df.at[0,'Price']=np.nan

In [97]:
df['Price'].dtype

dtype('float64')

In [98]:
df['Price'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [100]:
#Featuring Engeenering Start 
pd.date_range(start='2023-01-01',end='2023-03-01')

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10', '2023-02-11', '2023-02-12', '2023-02-13',
               '2023-02-14', '2023-02-15', '2023-02-16', '2023-02-17',
               '2023-02-18', '2023-02-19', '2023-02-20', '2023-02-21',
               '2023-02-22', '2023-02-23', '2023-02-24', '2023-02-25',
               '2023-02-26', '2023-02-27', '2023-02-28', '2023-03-01'],
              dtype='datetime64[ns]', freq='D')

In [43]:
#to create DataFrame of Data 
data=pd.DataFrame(pd.Series(pd.date_range(start='2023-01-01',end='2023-03-01')),columns=['Date'])

In [44]:
data

         Date
0  2023-01-01
1  2023-01-02
2  2023-01-03
3  2023-01-04
4  2023-01-05
5  2023-01-06
6  2023-01-07
7  2023-01-08
8  2023-01-09
9  2023-01-10
10 2023-01-11
11 2023-01-12
12 2023-01-13
13 2023-01-14
14 2023-01-15
15 2023-01-16
16 2023-01-17
17 2023-01-18
18 2023-01-19
19 2023-01-20
20 2023-01-21
21 2023-01-22
22 2023-01-23
23 2023-01-24
24 2023-01-25
25 2023-01-26
26 2023-01-27
27 2023-01-28
28 2023-01-29
29 2023-01-30
30 2023-01-31
31 2023-02-01
32 2023-02-02
33 2023-02-03
34 2023-02-04
35 2023-02-05
36 2023-02-06
37 2023-02-07
38 2023-02-08
39 2023-02-09
40 2023-02-10
41 2023-02-11
42 2023-02-12
43 2023-02-13
44 2023-02-14
45 2023-02-15
46 2023-02-16
47 2023-02-17
48 2023-02-18
49 2023-02-19
50 2023-02-20
51 2023-02-21
52 2023-02-22
53 2023-02-23
54 2023-02-24
55 2023-02-25
56 2023-02-26
57 2023-02-27
58 2023-02-28
59 2023-03-01

In [103]:
data['Date']

0    2023-01-01
1    2023-01-02
2    2023-01-03
3    2023-01-04
4    2023-01-05
5    2023-01-06
6    2023-01-07
7    2023-01-08
8    2023-01-09
9    2023-01-10
10   2023-01-11
11   2023-01-12
12   2023-01-13
13   2023-01-14
14   2023-01-15
15   2023-01-16
16   2023-01-17
17   2023-01-18
18   2023-01-19
19   2023-01-20
20   2023-01-21
21   2023-01-22
22   2023-01-23
23   2023-01-24
24   2023-01-25
25   2023-01-26
26   2023-01-27
27   2023-01-28
28   2023-01-29
29   2023-01-30
30   2023-01-31
31   2023-02-01
32   2023-02-02
33   2023-02-03
34   2023-02-04
35   2023-02-05
36   2023-02-06
37   2023-02-07
38   2023-02-08
39   2023-02-09
40   2023-02-10
41   2023-02-11
42   2023-02-12
43   2023-02-13
44   2023-02-14
45   2023-02-15
46   2023-02-16
47   2023-02-17
48   2023-02-18
49   2023-02-19
50   2023-02-20
51   2023-02-21
52   2023-02-22
53   2023-02-23
54   2023-02-24
55   2023-02-25
56   2023-02-26
57   2023-02-27
58   2023-02-28
59   2023-03-01
Name: Date, dtype: datetime64[ns]

In [104]:
data['Date'].dtypes

dtype('<M8[ns]')

In [105]:
data.dtypes

Date    datetime64[ns]
dtype: object

In [106]:
data['Date'].dt.day

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
30    31
31     1
32     2
33     3
34     4
35     5
36     6
37     7
38     8
39     9
40    10
41    11
42    12
43    13
44    14
45    15
46    16
47    17
48    18
49    19
50    20
51    21
52    22
53    23
54    24
55    25
56    26
57    27
58    28
59     1
Name: Date, dtype: int32

In [107]:
data['Day']=data['Date'].dt.day
data['Month']=data['Date'].dt.month
data['Year']=data['Date'].dt.year

In [109]:
data['Date'] <="2023-01-05"

0      True
1      True
2      True
3      True
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
58    False
59    False
Name: Date, dtype: bool

In [111]:
data[data['Date'] >="2023-01-05"]

         Date  Day  Month  Year
4  2023-01-05    5      1  2023
5  2023-01-06    6      1  2023
6  2023-01-07    7      1  2023
7  2023-01-08    8      1  2023
8  2023-01-09    9      1  2023
9  2023-01-10   10      1  2023
10 2023-01-11   11      1  2023
11 2023-01-12   12      1  2023
12 2023-01-13   13      1  2023
13 2023-01-14   14      1  2023
14 2023-01-15   15      1  2023
15 2023-01-16   16      1  2023
16 2023-01-17   17      1  2023
17 2023-01-18   18      1  2023
18 2023-01-19   19      1  2023
19 2023-01-20   20      1  2023
20 2023-01-21   21      1  2023
21 2023-01-22   22      1  2023
22 2023-01-23   23      1  2023
23 2023-01-24   24      1  2023
24 2023-01-25   25      1  2023
25 2023-01-26   26      1  2023
26 2023-01-27   27      1  2023
27 2023-01-28   28      1  2023
28 2023-01-29   29      1  2023
29 2023-01-30   30      1  2023
30 2023-01-31   31      1  2023
31 2023-02-01    1      2  2023
32 2023-02-02    2      2  2023
33 2023-02-03    3      2  2023
34 2023-02-04    4      2  2023
35 2023-02-05    5      2  2023
36 2023-02-06    6      2  2023
37 2023-02-07    7      2  2023
38 2023-02-08    8      2  2023
39 2023-02-09    9      2  2023
40 2023-02-10   10      2  2023
41 2023-02-11   11      2  2023
42 2023-02-12   12      2  2023
43 2023-02-13   13      2  2023
44 2023-02-14   14      2  2023
45 2023-02-15   15      2  2023
46 2023-02-16   16      2  2023
47 2023-02-17   17      2  2023
48 2023-02-18   18      2  2023
49 2023-02-19   19      2  2023
50 2023-02-20   20      2  2023
51 2023-02-21   21      2  2023
52 2023-02-22   22      2  2023
53 2023-02-23   23      2  2023
54 2023-02-24   24      2  2023
55 2023-02-25   25      2  2023
56 2023-02-26   26      2  2023
57 2023-02-27   27      2  2023
58 2023-02-28   28      2  2023
59 2023-03-01    1      3  2023

In [118]:
data[(data["Date"]>="2023-01-03" ) & (data["Date"]<="2023-01-11")]

         Date  Day  Month  Year
2  2023-01-03    3      1  2023
3  2023-01-04    4      1  2023
4  2023-01-05    5      1  2023
5  2023-01-06    6      1  2023
6  2023-01-07    7      1  2023
7  2023-01-08    8      1  2023
8  2023-01-09    9      1  2023
9  2023-01-10   10      1  2023
10 2023-01-11   11      1  2023

In [119]:
#Returns the Day Name 
data["Date"][0].day_name()

'Sunday'

In [120]:
#Returns the Month Name 
data["Date"][0].month_name()

'January'

In [123]:
data["Date"]

0    2023-01-01
1    2023-01-02
2    2023-01-03
3    2023-01-04
4    2023-01-05
5    2023-01-06
6    2023-01-07
7    2023-01-08
8    2023-01-09
9    2023-01-10
10   2023-01-11
11   2023-01-12
12   2023-01-13
13   2023-01-14
14   2023-01-15
15   2023-01-16
16   2023-01-17
17   2023-01-18
18   2023-01-19
19   2023-01-20
20   2023-01-21
21   2023-01-22
22   2023-01-23
23   2023-01-24
24   2023-01-25
25   2023-01-26
26   2023-01-27
27   2023-01-28
28   2023-01-29
29   2023-01-30
30   2023-01-31
31   2023-02-01
32   2023-02-02
33   2023-02-03
34   2023-02-04
35   2023-02-05
36   2023-02-06
37   2023-02-07
38   2023-02-08
39   2023-02-09
40   2023-02-10
41   2023-02-11
42   2023-02-12
43   2023-02-13
44   2023-02-14
45   2023-02-15
46   2023-02-16
47   2023-02-17
48   2023-02-18
49   2023-02-19
50   2023-02-20
51   2023-02-21
52   2023-02-22
53   2023-02-23
54   2023-02-24
55   2023-02-25
56   2023-02-26
57   2023-02-27
58   2023-02-28
59   2023-03-01
Name: Date, dtype: datetime64[ns]

In [126]:
data["day_name"]=data["Date"].dt.day_name()

In [128]:
data["day_month"]=data["Date"].dt.month_name()

In [129]:
data

         Date  Day  Month  Year   day_name day_month
0  2023-01-01    1      1  2023     Sunday   January
1  2023-01-02    2      1  2023     Monday   January
2  2023-01-03    3      1  2023    Tuesday   January
3  2023-01-04    4      1  2023  Wednesday   January
4  2023-01-05    5      1  2023   Thursday   January
5  2023-01-06    6      1  2023     Friday   January
6  2023-01-07    7      1  2023   Saturday   January
7  2023-01-08    8      1  2023     Sunday   January
8  2023-01-09    9      1  2023     Monday   January
9  2023-01-10   10      1  2023    Tuesday   January
10 2023-01-11   11      1  2023  Wednesday   January
11 2023-01-12   12      1  2023   Thursday   January
12 2023-01-13   13      1  2023     Friday   January
13 2023-01-14   14      1  2023   Saturday   January
14 2023-01-15   15      1  2023     Sunday   January
15 2023-01-16   16      1  2023     Monday   January
16 2023-01-17   17      1  2023    Tuesday   January
17 2023-01-18   18      1  2023  Wednesday   January
18 2023-01-19   19      1  2023   Thursday   January
19 2023-01-20   20      1  2023     Friday   January
20 2023-01-21   21      1  2023   Saturday   January
21 2023-01-22   22      1  2023     Sunday   January
22 2023-01-23   23      1  2023     Monday   January
23 2023-01-24   24      1  2023    Tuesday   January
24 2023-01-25   25      1  2023  Wednesday   January
25 2023-01-26   26      1  2023   Thursday   January
26 2023-01-27   27      1  2023     Friday   January
27 2023-01-28   28      1  2023   Saturday   January
28 2023-01-29   29      1  2023     Sunday   January
29 2023-01-30   30      1  2023     Monday   January
30 2023-01-31   31      1  2023    Tuesday   January
31 2023-02-01    1      2  2023  Wednesday  February
32 2023-02-02    2      2  2023   Thursday  February
33 2023-02-03    3      2  2023     Friday  February
34 2023-02-04    4      2  2023   Saturday  February
35 2023-02-05    5      2  2023     Sunday  February
36 2023-02-06    6      2  2023     Monday  February
37 2023-02-07    7      2  2023    Tuesday  February
38 2023-02-08    8      2  2023  Wednesday  February
39 2023-02-09    9      2  2023   Thursday  February
40 2023-02-10   10      2  2023     Friday  February
41 2023-02-11   11      2  2023   Saturday  February
42 2023-02-12   12      2  2023     Sunday  February
43 2023-02-13   13      2  2023     Monday  February
44 2023-02-14   14      2  2023    Tuesday  February
45 2023-02-15   15      2  2023  Wednesday  February
46 2023-02-16   16      2  2023   Thursday  February
47 2023-02-17   17      2  2023     Friday  February
48 2023-02-18   18      2  2023   Saturday  February
49 2023-02-19   19      2  2023     Sunday  February
50 2023-02-20   20      2  2023     Monday  February
51 2023-02-21   21      2  2023    Tuesday  February
52 2023-02-22   22      2  2023  Wednesday  February
53 2023-02-23   23      2  2023   Thursday  February
54 2023-02-24   24      2  2023     Friday  February
55 2023-02-25   25      2  2023   Saturday  February
56 2023-02-26   26      2  2023     Sunday  February
57 2023-02-27   27      2  2023     Monday  February
58 2023-02-28   28      2  2023    Tuesday  February
59 2023-03-01    1      3  2023  Wednesday     March

In [135]:

ld=[]

for i in data['Date']:
    print(ld.append(i.day_name()))
    data["Date"]=ld.appendi.day_name()

None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday']

In [136]:
data

         Date  Day  Month  Year   day_name day_month
0  2023-01-01    1      1  2023     Sunday   January
1  2023-01-02    2      1  2023     Monday   January
2  2023-01-03    3      1  2023    Tuesday   January
3  2023-01-04    4      1  2023  Wednesday   January
4  2023-01-05    5      1  2023   Thursday   January
5  2023-01-06    6      1  2023     Friday   January
6  2023-01-07    7      1  2023   Saturday   January
7  2023-01-08    8      1  2023     Sunday   January
8  2023-01-09    9      1  2023     Monday   January
9  2023-01-10   10      1  2023    Tuesday   January
10 2023-01-11   11      1  2023  Wednesday   January
11 2023-01-12   12      1  2023   Thursday   January
12 2023-01-13   13      1  2023     Friday   January
13 2023-01-14   14      1  2023   Saturday   January
14 2023-01-15   15      1  2023     Sunday   January
15 2023-01-16   16      1  2023     Monday   January
16 2023-01-17   17      1  2023    Tuesday   January
17 2023-01-18   18      1  2023  Wednesday   January
18 2023-01-19   19      1  2023   Thursday   January
19 2023-01-20   20      1  2023     Friday   January
20 2023-01-21   21      1  2023   Saturday   January
21 2023-01-22   22      1  2023     Sunday   January
22 2023-01-23   23      1  2023     Monday   January
23 2023-01-24   24      1  2023    Tuesday   January
24 2023-01-25   25      1  2023  Wednesday   January
25 2023-01-26   26      1  2023   Thursday   January
26 2023-01-27   27      1  2023     Friday   January
27 2023-01-28   28      1  2023   Saturday   January
28 2023-01-29   29      1  2023     Sunday   January
29 2023-01-30   30      1  2023     Monday   January
30 2023-01-31   31      1  2023    Tuesday   January
31 2023-02-01    1      2  2023  Wednesday  February
32 2023-02-02    2      2  2023   Thursday  February
33 2023-02-03    3      2  2023     Friday  February
34 2023-02-04    4      2  2023   Saturday  February
35 2023-02-05    5      2  2023     Sunday  February
36 2023-02-06    6      2  2023     Monday  February
37 2023-02-07    7      2  2023    Tuesday  February
38 2023-02-08    8      2  2023  Wednesday  February
39 2023-02-09    9      2  2023   Thursday  February
40 2023-02-10   10      2  2023     Friday  February
41 2023-02-11   11      2  2023   Saturday  February
42 2023-02-12   12      2  2023     Sunday  February
43 2023-02-13   13      2  2023     Monday  February
44 2023-02-14   14      2  2023    Tuesday  February
45 2023-02-15   15      2  2023  Wednesday  February
46 2023-02-16   16      2  2023   Thursday  February
47 2023-02-17   17      2  2023     Friday  February
48 2023-02-18   18      2  2023   Saturday  February
49 2023-02-19   19      2  2023     Sunday  February
50 2023-02-20   20      2  2023     Monday  February
51 2023-02-21   21      2  2023    Tuesday  February
52 2023-02-22   22      2  2023  Wednesday  February
53 2023-02-23   23      2  2023   Thursday  February
54 2023-02-24   24      2  2023     Friday  February
55 2023-02-25   25      2  2023   Saturday  February
56 2023-02-26   26      2  2023     Sunday  February
57 2023-02-27   27      2  2023     Monday  February
58 2023-02-28   28      2  2023    Tuesday  February
59 2023-03-01    1      3  2023  Wednesday     March

In [138]:
asus=df[df['brand']=="ASUS"]
asus['Price'].min()

17990.0

In [148]:
bb=df['brand'].unique()
lst=df['brand'].unique()

In [150]:
for i in bb:
    lt=df[df["brand"]==i]
    mt=lt['Price'].min()
    print(i,"==>",mt)

ASUS ==> 17990.0
Lenovo ==> 16990.0
acer ==> 23990.0
Avita ==> 17490.0
HP ==> 26470.0
DELL ==> 35990.0
MSI ==> 38990.0
APPLE ==> 85990.0

In [ ]:
###Groupby

In [151]:
brand_group=df.groupby("brand")
brand_group

In [155]:
brand_group.get_group("HP")

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
15,HP,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,No,56490.0,3 stars,0,0
16,HP,Intel,Core i5,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,65390.0,3 stars,0,0
18,HP,Intel,Celeron Dual,Not Available,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,32490.0,4 stars,58,6
22,HP,Intel,Core i3,7th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,32955.0,4 stars,311,27
23,HP,Intel,Core i5,7th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,46200.0,4 stars,47,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
776,HP,AMD,Ryzen 7,Not Available,16 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,Yes,Yes,92990.0,3 stars,0,0
777,HP,AMD,Ryzen 7,Not Available,16 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,84190.0,3 stars,0,0
782,HP,AMD,Ryzen 7,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,8 GB,Casual,1 year,No,No,159990.0,4 stars,17,2
792,HP,AMD,Ryzen 7,Not Available,16 GB,DDR4,256 GB,1024 GB,Windows,64-bit,4 GB,Gaming,1 year,No,Yes,75990.0,4 stars,1084,123
807,HP,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,8 GB,Casual,1 year,No,Yes,141990.0,3 stars,0,0

In [156]:
brand_group['Price'].min()

brand
APPLE     85990.0
ASUS      17990.0
Avita     17490.0
DELL      35990.0
HP        26470.0
Lenovo    16990.0
MSI       38990.0
acer      23990.0
Name: Price, dtype: float64

In [157]:
brand_group['Price'].max()

brand
APPLE     309990.0
ASUS      441990.0
Avita      73990.0
DELL      139990.0
HP        239759.0
Lenovo    265998.0
MSI       291190.0
acer      169990.0
Name: Price, dtype: float64

In [158]:
brand_group.get_group('acer')['Price'].max()

169990.0

In [45]:
final_analysis=brand_group['Price'].agg(["count","min","max","mean","sum"])

NameError: name 'brand_group' is not defined

In [3]:
#11-01-2025
import pandas as pd

# Create the dataset
data = {
    "Name": ["John", "Alice", "Bob", "Emma"],
    "Department": ["IT", "HR", "Marketing","IT"],
    "Salary": [60000, 75000, 50000, 65000]
}
df = pd.DataFrame(data)

# Use map to add a prefix to the Department names
df["Name"] = df["Name"].map(lambda x: "Shri " + x)

df

         Name Department  Salary
0   Shri John         IT   60000
1  Shri Alice         HR   75000
2    Shri Bob  Marketing   50000
3   Shri Emma         IT   65000

In [4]:
df["Salary"] = df["Salary"].map(lambda x: 100 + x)

In [5]:
df

         Name Department  Salary
0   Shri John         IT   60100
1  Shri Alice         HR   75100
2    Shri Bob  Marketing   50100
3   Shri Emma         IT   65100

In [6]:
df["Salary"]=df["Salary"].apply(lambda x:x*1.10)

In [7]:
df

         Name Department   Salary
0   Shri John         IT  66110.0
1  Shri Alice         HR  82610.0
2    Shri Bob  Marketing  55110.0
3   Shri Emma         IT  71610.0

In [12]:
#apply row-wise to combine "Name" and "department"
df["employee_info"]=df.apply(lambda row : f"{row["Name"]} ({row["Department"]})",axis=1)

In [13]:
df

         Name Department   Salary         employee_info
0   Shri John         IT  66110.0        Shri John (IT)
1  Shri Alice         HR  82610.0       Shri Alice (HR)
2    Shri Bob  Marketing  55110.0  Shri Bob (Marketing)
3   Shri Emma         IT  71610.0        Shri Emma (IT)

In [129]:
# Low: Salary < 60000
# Medium: 60000 >= Salary <= 70000
# High: Salary ≥ 70000

def categorize_salary(row):
    if row["Salary"] < 60000:
        return "Low"
    elif ( row["Salary"] >= 60000 ) and ( row["Salary"] <= 70000 ):
        return "Medium"
    else:
        return "High"

df["Salary_Category"] = df.apply(categorize_salary, axis=1)
df

,Name,Department,Salary,Bonus,Employee_Info,A,B,Salary_Category
0,John,IT,60000,5000,John IT,John,IT,Medium
1,Alice,HR,75000,updated,Alice HR,Alice,HR,High
2,Bob,Marketing,50000,3000,Bob Marketing,Bob,Marketing,Low
3,Emma,IT,65000,6000,Emma IT,Emma,IT,Medium
4,Sophia,HR,72000,6500,Sophia HR,Sophia,HR,High
5,James,Marketing,55000,3500,James Marketing,James,Marketing,Low

In [130]:
df["Name"].apply(len)

0    4
1    5
2    3
3    4
4    6
5    5
Name: Name, dtype: int64

In [16]:
df["Name"].map(len)

0     9
1    10
2     8
3     9
Name: Name, dtype: int64

TypeError: DataFrame.apply() missing 1 required positional argument: 'func'

In [19]:
####Pivot table

data = {
    "Name": ["John", "Alice", "Bob", "Emma", "Sophia", "James"],
    "Department": ["IT", "HR", "Marketing", "IT", "HR", "Marketing"],
    "Salary": [60000, 75000, 50000, 65000, 72000, 55000],
    "Bonus": [5000, 7000, 3000, 6000, 6500, 3500]
}
df = pd.DataFrame(data)
df

     Name Department  Salary  Bonus
0    John         IT   60000   5000
1   Alice         HR   75000   7000
2     Bob  Marketing   50000   3000
3    Emma         IT   65000   6000
4  Sophia         HR   72000   6500
5   James  Marketing   55000   3500

In [21]:
pivot = pd.pivot_table(
    df,
    values=["Salary", "Bonus"],     
    index="Department",            
    aggfunc={"Salary": "mean", "Bonus": "sum"}  # Aggregation functions
)
pivot

            Bonus   Salary
Department
HR          13500  73500.0
IT          11000  62500.0
Marketing    6500  52500.0

In [22]:
df

     Name Department  Salary  Bonus
0    John         IT   60000   5000
1   Alice         HR   75000   7000
2     Bob  Marketing   50000   3000
3    Emma         IT   65000   6000
4  Sophia         HR   72000   6500
5   James  Marketing   55000   3500

In [23]:
df.sort_values(by="Salary")

     Name Department  Salary  Bonus
2     Bob  Marketing   50000   3000
5   James  Marketing   55000   3500
0    John         IT   60000   5000
3    Emma         IT   65000   6000
4  Sophia         HR   72000   6500
1   Alice         HR   75000   7000

In [24]:
df.sort_values(by="Salary",ascending=False)

     Name Department  Salary  Bonus
1   Alice         HR   75000   7000
4  Sophia         HR   72000   6500
3    Emma         IT   65000   6000
0    John         IT   60000   5000
5   James  Marketing   55000   3500
2     Bob  Marketing   50000   3000

In [25]:
df.sample()

   Name Department  Salary  Bonus
3  Emma         IT   65000   6000

In [27]:
df.sample(3)  #randam sampleing

    Name Department  Salary  Bonus
1  Alice         HR   75000   7000
0   John         IT   60000   5000
5  James  Marketing   55000   3500

In [28]:
df.shape

(6, 4)

In [29]:
df2=df.sample(6)

In [34]:
df2

     Name Department  Salary  Bonus
4  Sophia         HR   72000   6500
5   James  Marketing   55000   3500
3    Emma         IT   65000   6000
0    John         IT   60000   5000
1   Alice         HR   75000   7000
2     Bob  Marketing   50000   3000

In [36]:
df2.reset_index()

   index    Name Department  Salary  Bonus
0      4  Sophia         HR   72000   6500
1      5   James  Marketing   55000   3500
2      3    Emma         IT   65000   6000
3      0    John         IT   60000   5000
4      1   Alice         HR   75000   7000
5      2     Bob  Marketing   50000   3000

In [37]:
df2.sort_index() #sort your data based on the index

     Name Department  Salary  Bonus
0    John         IT   60000   5000
1   Alice         HR   75000   7000
2     Bob  Marketing   50000   3000
3    Emma         IT   65000   6000
4  Sophia         HR   72000   6500
5   James  Marketing   55000   3500

In [38]:
df2.sort_index(ascending=False) #sort your data based on the index

     Name Department  Salary  Bonus
5   James  Marketing   55000   3500
4  Sophia         HR   72000   6500
3    Emma         IT   65000   6000
2     Bob  Marketing   50000   3000
1   Alice         HR   75000   7000
0    John         IT   60000   5000

In [90]:
df.sample(6)

     Name Department  Salary  Bonus
2     Bob  Marketing   50000   3000
4  Sophia         HR   72000   6500
0    John         IT   60000   5000
1   Alice         HR   75000   7000
5   James  Marketing   55000   3500
3    Emma         IT   65000   6000

In [92]:
df.sample(8)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [117]:
df.sample(8,replace=True)

     Name Department  Salary  Bonus
5   James  Marketing   55000   3500
4  Sophia         HR   72000   6500
4  Sophia         HR   72000   6500
2     Bob  Marketing   50000   3000
5   James  Marketing   55000   3500
4  Sophia         HR   72000   6500
1   Alice         HR   75000   7000
0    John         IT   60000   5000

In [119]:
df["Name"].str.replace('a'," ")

0      John
1     Alice
2       Bob
3      Emm
4    Sophi
5     J mes
Name: Name, dtype: object

In [120]:
df["Employee_Info"] = df.apply(lambda row: f"{row['Name']} {row['Department']}", axis=1)
df

     Name Department  Salary  Bonus    Employee_Info
0    John         IT   60000   5000          John IT
1   Alice         HR   75000   7000         Alice HR
2     Bob  Marketing   50000   3000    Bob Marketing
3    Emma         IT   65000   6000          Emma IT
4  Sophia         HR   72000   6500        Sophia HR
5   James  Marketing   55000   3500  James Marketing

In [121]:
df["Employee_Info"].str.split()

0            [John, IT]
1           [Alice, HR]
2      [Bob, Marketing]
3            [Emma, IT]
4          [Sophia, HR]
5    [James, Marketing]
Name: Employee_Info, dtype: object

In [122]:
df["Employee_Info"].str.split(expand=True)

        0          1
0    John         IT
1   Alice         HR
2     Bob  Marketing
3    Emma         IT
4  Sophia         HR
5   James  Marketing

In [123]:
df[["A","B"]]=df["Employee_Info"].str.split(expand=True)

In [124]:
df

     Name Department  Salary  Bonus    Employee_Info       A          B
0    John         IT   60000   5000          John IT    John         IT
1   Alice         HR   75000   7000         Alice HR   Alice         HR
2     Bob  Marketing   50000   3000    Bob Marketing     Bob  Marketing
3    Emma         IT   65000   6000          Emma IT    Emma         IT
4  Sophia         HR   72000   6500        Sophia HR  Sophia         HR
5   James  Marketing   55000   3500  James Marketing   James  Marketing

In [125]:
pd.__version__

'2.2.2'

In [1]:
pip show pandas

Name: pandas
Version: 2.2.2
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
All rights reserved.

Copyright (c) 2011-2023, Open source contributors.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Location: c:\Users\om\AppData\Local\Programs\Python\Python312\Lib\site-packages
Requires: numpy, python-dateutil, pytz, tzdata
Required-by: fitz, seaborn
Note: you may need to restart the kernel to use updated packages.

In [131]:
 df.at[1,"Bonus"]="updated" #data manupulations

In [1]:
df

NameError: name 'df' is not defined